import type { Metadata } from "next";
import { Poppins, Reenie_Beanie } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/CommonComponents/ThemeProvider";
import QueryProvider from "@/QueryProvider";
import SessionProvider from "@/app/SessionProvider";
import GlobalSpinner from "@/components/CommonComponents/GlobalSpinner";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-poppins",
  display: "swap",
});

const reenie = Reenie_Beanie({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-reenie",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${poppins.variable} ${reenie.variable} antialiased`}
        suppressHydrationWarning
      >
        <ThemeProvider>
          <SessionProvider>
            <QueryProvider>
              {children}
              <GlobalSpinner />
            </QueryProvider>
          </SessionProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
