import type { Metadata } from "next";
import ClientRootLayout from "./ClientLayout";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <ClientRootLayout>{children}</ClientRootLayout>
    </html>
  );
}
