import type { Metadata } from "next";
import { Poppins, Reenie_Beanie } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/CommonComponents/ThemeProvider";
import QueryProvider from "@/QueryProvider";
import SessionProvider from "@/app/SessionProvider";
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-poppins",
});

const reenie = Reenie_Beanie({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-reenie",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${poppins.variable} ${reenie.variable} antialiased`}>
        <ThemeProvider>
          <SessionProvider>
            <QueryProvider>{children}</QueryProvider>
          </SessionProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
